### ISSUE TITLE
Could you please implement BiG-World-Fixpack fixes?

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/bg2-wildmage#1]
Hi,
Could you please implement BiG-World-Fixpack fixes?
https://github.com/BiGWorldProject/BiG-World-Fixpack/tree/master/BiG%20World%20Fixpack/WildMage

**Comment by burner1024** [comment]
Well, they are mostly implemented, except for HANDLE_CHARSETS thing... I'm not sure what does it do.

**Comment by ALIENQuake** [comment]
Well, it's most important thing regarding EE compatibility. Without implementing HANDLE_CHARSETS, if you choose any other language than English for EE games, it will crash because of the ANSI strings (EE needs UTF-8, BG2/BGT needs ANSI) You can find documentation in weidu readme or take look at the exameple https://github.com/UnearthedArcana/refinements/pull/2/commits/8df343615f3aa0586f5a21ac71335c4f1b5a6409#diff-61d9a6f855db558c8ba0f3112eb6b300L97

**Comment by ALIENQuake** [comment]
I see that you omit EET compatibility code, any reason?

**Comment by burner1024** [comment]
No, I just don't have EET, it's not out yet, is it?
HANDLE_CHARSETS seems unnecessarily complicated to me. I'd think Weidu would just do it under the hood.
I'll get to this soon.

**Comment by ALIENQuake** [comment]
EET is out: http://gibberlings3.net/forums/index.php?showforum=195
You can read more about HANDLE_CHARSETS here http://forums.pocketplane.net/index.php?
topic=29193.5
About " unnecessarily complicated " - c'mon... when you are dealing with some crazy hexadecibal byte conversion, EE engine features, Opcodes, correct order of the commands etc I'm sure that implementing one function cannot be real problem ;)

**Comment by burner1024** [comment]
OK, sorry it took so long, but finally it's all in.
BTW, new version needs some [translation updates](https://tra.bgforge.net/projects/baldurs-gate/wild-mage-additions/).

**Comment by ALIENQuake** [comment]
Hey, no need to be sorry. Some waited to mods receive updates for 3+ years ;) The good news is that I will remove wildmage patches because I think that I'm the only one who is aware about this repository ;) The bad news is that I will no longer maintain BWS and Big-World-Fixpack. Thanks for you support.
