### ISSUE TITLE
Cannot install on EET

### ISSUE THREAD

**Issue by Niewiemu** [BGforgeNet/bg2-wildmage#18]
Hi
On latest release when I try to install I get this fail

ERROR: Sys_error("wildmage/lib/bgforge/main.tpa: No such file or directory")
Please make a backup of the file: SETUP-WILDMAGE.DEBUG and look for support at: https://github.com/BGforgeNet/bg2-wildmage/issues
Automatically Skipping [New Wild Magic Spells -> Ironman] because of error.
Using Language [English]

SKIPPING: [Retain Rhialto's items]
	You must have "New Wild Magic Spells" installed!
weidu_external/lang/english/setup.tra file not found. Skipping...

NOT INSTALLED DUE TO ERRORS New Wild Magic Spells -> Ironman

Thank you for help in advance!

**Comment by Niewiemu** [comment]
Never mind that - I downloaded lastest github instead of released version - fixed that myself :)

**Comment by burner1024** [comment]
What did you download the first time and how were you installing it?

Edit, ah, got it, it's the other way round, you downloaded source code first. All's good then.
