### ISSUE TITLE
Wild Mage Additions 2.1 has no Project Infinity text labels for its components!

### ISSUE THREAD

**Issue by Endarire** [BGforgeNet/bg2-wildmage#19]
Greetings, all, including @bgforge-weblate!

Project Infinity has no text labels for its components.  I wan to be able to install this mod with PI, but don't trust the unidentified strings enough to do so yet.

Thankee for fixing this!

![image](https://user-images.githubusercontent.com/10439725/134282960-f7e68e86-752b-44c2-b567-093cad113407.png)

**Comment by burner1024** [comment]
This is probably the same as https://github.com/BGforgeNet/bg2-uniqueartifacts/commit/ce93ddf76ab85a183890a6ea70110026bdbf2e7a.
@ALIENQuake I don't see an issue opened in weidu repo about this, is there one?
(Also I see that you replaced first `MOD_FOLDER`, but not the second one in the same string, is that correct?)

**Comment by ALIENQuake** [comment]
@burner1024 
Hi, fix should replace all %MOD_FOLDER% for LANGUAGE keyword, the bg2-uniqueartifacts mod was fixed in later commits. This one is fixed by https://github.com/BGforgeNet/bg2-wildmage/pull/20

**Comment by burner1024** [comment]
Cool, but where is the weidu bug reported?

**Comment by ALIENQuake** [comment]
@burner1024 The bug report for WeiDU 247 is here: https://forums.pocketplane.net/index.php?topic=29957.msg340390

**Comment by burner1024** [comment]
Got it, thanks
