### ISSUE TITLE
Latest Release: Blade Shower Didn't Work

### ISSUE THREAD

**Issue by Endarire** [BGforgeNet/bg2-wildmage#21]
Greetings, @bgforge-hive!

Today I tested the latest release of Wild Mage Additions.  Various spells were amusing and most spells I tested worked as intended.  However, _blade shower_, after being cast, added the Blade Shower innate ability to my character's innate abilities area but I was prevented from selecting a target.  I couldn't cast it on foes, friends, nor self.

Thankee for fixing this!

**Comment by burner1024** [comment]
How do you mean? Show screenshot.

**Comment by Endarire** [comment]
I tested with a character who had 5 million EXP (level 23).

![image](https://github.com/BGforgeNet/bg2-wildmage/assets/10439725/7cfdf30e-2764-4a85-b358-924300e8291b)

I can prepare & cast the spell.

![image](https://github.com/BGforgeNet/bg2-wildmage/assets/10439725/0e46ddd3-4a7d-4692-af1b-0d6e99e15faf)

I get the Blade Shower innate ability.

![image](https://github.com/BGforgeNet/bg2-wildmage/assets/10439725/780890d3-0170-4140-8069-af0fec4de226)

Using the innate ability brings up a target for the spell.

![image](https://github.com/BGforgeNet/bg2-wildmage/assets/10439725/35290f58-8084-4009-b028-f43c1b9106a9)

Clicking my character didn't work.

![image](https://github.com/BGforgeNet/bg2-wildmage/assets/10439725/054d9d7f-7b23-4a47-a9e2-941b1bf83136)

Clicking a foe didn't work, and if I keep clicking a creature I'll either try to interact or attack.

Thankee!

**Comment by burner1024** [comment]
I still don't understand what do you mean by don't work.
It has charges, so you have to click the exact number of time to spend them.

**Comment by Endarire** [comment]
Once you explained to me how to use the innate ability, I used the innate ability, clicked a gnoll a buncha times, and a dart flew out at it.  I just assumed the spell would work like a typical _magic missile_:  I cast the spell on a target and it does damage or applies its effect without having to repeatedly click like this.  While I have barely used this spell, I have not understood the benefit of repeatedly clicking a target to have it cast compared to just doing this the typical way.

Thankee!

**Comment by burner1024** [comment]
It works like Wand of Lightning, so you can select multiple targets should you wish.
