### ISSUE TITLE
pansy mode bug

### ISSUE THREAD

**Issue by OverDrone** [BGforgeNet/bg2-wildmage#9]
Hello!
When you choose pansy mode for EET, setup does not work correctly. it creates file with % in name. 
And Rialto doesn't spawn obviously...
wildmage/main.tph "if" section should change out_candlekeep_area variable in all cases. 
I've created pull request for it https://github.com/BGforgeNet/bg2-wildmage/pull/10

**Comment by burner1024** [comment]
It appears that stationary wouldn't work at all then. I didn't notice that, because I always use ironman. I must've screwed that when re-implementing BWP patches.
Thank you for the pull, it's merged.
